SHELL=/bin/sh


TNAME = indexer
SRC = ./src


all: ; cd $(SRC) ; make all ; cp indexer ../bin/indexer


debug: ; cd $(SRC) ; make debug ; cp indexer ../bin/indexer

clean: ; cd $(SRC) ; make clean


cleanall: ; cd $(SRC) ; make cleanall

